[package]
name = "gravity"
version = "0.1.0"
authors = ["G. Endignoux <ggendx@gmail.com>"]
edition = "2024"
rust-version = "1.85.0"

[features]
bigbench = []

[dependencies]
arrayref = "0.3.9"
byteorder = "1.5.0"
sha2 = "0.10.9"

[dev-dependencies]
hex = "0.4.3"
